languageCode = "en-us"
title = "Andrew Krivak"
baseurl = "http://andrewkrivak.com"
theme = "authorsite"
metaDataFormat = "yaml"
log = true
[params]
    featured_blurb_for_books_page = "Some writers are good at drawing a literary curtain over reality, and then there are writers who raise the veil and lead us to see for the first time. Krivák belongs to the latter. The Sojourn, about a war and a family and coming-of-age, does not present a single false moment of sentimental creation. Rather, it looks deeply into its characters' lives with wisdom and humanity, and, in doing so, helps us experience a distant past that feels as if it could be our own. – National Book Awards Judges’ Citation for The Sojourn (2011 Fiction Finalist)"

[permalinks]
  page = "/:title/"
  about = "/:filename/"

[[menu.main]]
    name = "about"
    weight = 0
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "books"
    identifier = "books"
    weight = 1
    url = "/book/"
[[menu.main]]
    name = "contact"
    identifier = "contact"
    weight = 2
    url = "/contact/"
[[menu.main]]
    name = "journal"
    identifier = "journal"
    weight = 3
    url = "/journal/"
[[menu.main]]
    name = "events"
    identifier = "events"
    weight = 4
    url = "/event/"
