---
upload_path: "/static/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  review:
    default_front_matter_template: review
  event:
    default_front_matter_template: event
  book:
    default_front_matter_template: book
version: 0.38.1
