---
label: default
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: tags
  label: Tags
  type: text
  hidden: false
  default: 
- name: images
  label: Images
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
pages:
- content/journal/the-signal-flame-is-among-the-finalists-for-the-2018-chautauqua-prize..md
